version: '3'

services:
  api-with-model:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-with-model
    ports:
      - 8000:8000
    healthcheck:
      test:
        # Test the health of the container using curl with fake data to predict 
        - CMD
        - curl -x POST http://localhost:8000/predict
        - -H
        - 'Content-Type: application/json'
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  default:
    name: mlops-network
    external: true
