channels:
- conda-forge
dependencies:
- python=3.11.0
- pip<=24.0
- pip:
  - mlflow==2.13.2
  - cloudpickle==2.2.1
  - numpy==1.26.3
  - packaging==21.3
  - psutil==5.9.7
  - pyyaml==6.0.1
  - scikit-learn==1.4.2
  - scipy==1.12.0
name: mlflow-env
